
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_BMA222E_NEW),y)
obj-y	+=  bma222E-new/
endif

ifeq ($(CONFIG_MTK_KXTJ2_1009_NEW),y)
obj-y	+=  KXTJ2_1009-new/
endif
